from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .caption_node import NODE_CLASS_MAPPINGS_CAPTION, NODE_DISPLAY_NAME_MAPPINGS_CAPTION
from .caption_options import NODE_CLASS_MAPPINGS_OPTIONS, NODE_DISPLAY_NAME_MAPPINGS_OPTIONS
from .batch_prompt_node import NODE_CLASS_MAPPINGS_BATCH_PROMPT, NODE_DISPLAY_NAME_MAPPINGS_BATCH_PROMPT
from .local_api_common_nodes import (
    NODE_CLASS_MAPPINGS_LOCAL_API_COMMON,
    NODE_DISPLAY_NAME_MAPPINGS_LOCAL_API_COMMON,
)
from .multi_turn_chat_node import NODE_CLASS_MAPPINGS_MULTI, NODE_DISPLAY_NAME_MAPPINGS_MULTI
from .skill_loader_node import NODE_CLASS_MAPPINGS_SKILL, NODE_DISPLAY_NAME_MAPPINGS_SKILL

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS,
    **NODE_CLASS_MAPPINGS_CAPTION,
    **NODE_CLASS_MAPPINGS_OPTIONS,
    **NODE_CLASS_MAPPINGS_BATCH_PROMPT,
    **NODE_CLASS_MAPPINGS_LOCAL_API_COMMON,
    **NODE_CLASS_MAPPINGS_MULTI,
    **NODE_CLASS_MAPPINGS_SKILL,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS,
    **NODE_DISPLAY_NAME_MAPPINGS_CAPTION,
    **NODE_DISPLAY_NAME_MAPPINGS_OPTIONS,
    **NODE_DISPLAY_NAME_MAPPINGS_BATCH_PROMPT,
    **NODE_DISPLAY_NAME_MAPPINGS_LOCAL_API_COMMON,
    **NODE_DISPLAY_NAME_MAPPINGS_MULTI,
    **NODE_DISPLAY_NAME_MAPPINGS_SKILL,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
